### PR TITLE
Update templates to match with current Django Admin

### PR DESCRIPTION
**Pull request by nikhilweee**
This PR updates templates to better match with those of Django 4.2

### CODE REVIEW

**Comment by nikhilweee** [comment]
@selwin Would be nice to hear your thoughts and hopefully get this merged soon.

**Comment by selwin** [comment]
Hi @nikhilweee mind attaching a screenshot of before and after?

**Comment by selwin** [comment]
And how does this change affect Django < 4.2?

**Comment by nikhilweee** [comment]
This is what `/django_rq/queue/` looked like before

image

This is what `/django_rq/queue/` looks like after this PR

image

---
The difference is subtle here, but is more pronounced in the next template

---

This is what `/django-rq/queues/0/scheduled/` looked like before

image

This is what `/django-rq/queues/0/scheduled/` looks like after this PR

image

**Comment by nikhilweee** [comment]
@selwin My changes are based off of the current [`change_list.html`](https://github.com/django/django/blob/main/django/contrib/admin/templates/admin/change_list.html) template.

I am not sure about the impact on Django < 4.2, but comparing v3.2.20 to v4.2.4 on GitHub, looks like that page hasn't changed. So I am tempted to say it's safe to assume that this PR should be applicable to both Django 3.2 and 4.2?

https://github.com/django/django/compare/4.2.4...3.2.20

**Comment by selwin** [comment]
Do you mind testing this change on Django 3.2 at the very least? We don't have unit tests for this so I'd feel much more comfortable if I can see a screenshot of how it looks on older versions.

**Comment by nikhilweee** [comment]
@selwin Here are results on Django 3.2

`django_rq/queue` Before this PR

image

`django_rq/queue` After this PR

image

---

`django_rq/queues/0/scheduled` Before this PR

image

`django_rq/queues/0/scheduled` After this PR

image

**Comment by nikhilweee** [comment]
Hey @selwin, any thoughts?

**Comment by selwin** [comment]
Thanks!

**Pull request merged**
