### PR TITLE
support Django 3.0 (remove dependency on django.utils.six + fix load admin_static)

### LINKED ISSUE #382: Django 3.0 Compatibility
I just upgraded to Django 3.0 and this failed for my project with the following exception:

```
Traceback (most recent call last):
  File "/Users/dneuhaeuser/dev/pricing-steering/manage.py", line 21, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/dneuhaeuser/dev/pricing-steering/.tox/py37/lib/python3.7/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/Users/dneuhaeuser/dev/pricing-steering/.tox/py37/lib/python3.7/site-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/Users/dneuhaeuser/dev/pricing-steering/.tox/py37/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/dneuhaeuser/dev/pricing-steering/.tox/py37/lib/python3.7/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/Users/dneuhaeuser/dev/pricing-steering/.tox/py37/lib/python3.7/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/Users/dneuhaeuser/dev/pricing-steering/.tox/py37/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/dneuhaeuser/dev/pricing-steering/.tox/py37/lib/python3.7/site-packages/django_rq/__init__.py", line 3, in <module>
    from .decorators import job
  File "/Users/dneuhaeuser/dev/pricing-steering/.tox/py37/lib/python3.7/site-packages/django_rq/decorators.py", line 4, in <module>
    from django.utils import six
ImportError: cannot import name 'six' from 'django.utils' (/Users/dneuhaeuser/dev/pricing-steering/.tox/py37/lib/python3.7/site-packages/django/utils/__init__.py)
```

This looks like django-rq isn't compatible with Django 3.0, yet. It would be great, if that could be fixed.

### PR DESCRIPTION
**Pull request by terencehonles**
Fixes #382 without pulling in `six` explicitly.

Probably needed for #383.

### CODE REVIEW

**Comment by terencehonles** [comment]
Depends on niwinz/django-redis#401

**Comment by terencehonles** [comment]
Not sure how more `admin_static` were introduced or if they were just missed in #315 but they are addressed now.

**Comment by selwin** [comment]
Tests for django 3.0 still fails. Mind updating this PR?

**Comment by selwin** [comment]
It seems like the tests fail the PyPI version of django-redis does not yet support Django 3.0. It's fixed in this commit: https://github.com/niwinz/django-redis/commit/2ab2f5647dc69a4bf1357380aabb7b479e878b00 . The test should pass if you get CircleCI to pull in django-redis' master branch to run tests on.

**Comment by hugorodgerbrown** [comment]
I have updated #384 to pull in the changes in this PR, as well as dropping support for Django 1 and Python 2.

**Comment by selwin** [comment]
Fixed in https://github.com/rq/django-rq/pull/384

**Comment by terencehonles** [comment]
Thanks for updating your PR to not pull in six @hugorodgerbrown (looks like @selwin also commented on that).

@selwin I hadn't pulled in master because I figured we'd want to build against a released version of django-redis.

Sorry for not being able to update my PR and help w/ the tests, but it looks like you guys took care of it :muscle:

**Pull request closed without merging**
